### ISSUE TITLE
Not really an issue...comment/question

### ISSUE THREAD

**Issue by qwkynuf** [clwgh/piaware-sitetotals#1]
I have never really worked in git before, so I probably did it wrong, but I downloaded your code, made a couple of edits, and uploaded a new version.

So, apologies in advance.

You are welcome to use any of my suggestions, or not. I definitely plan to take advantage of your good start and use my edits to get a little bit more out of it.

Thanks!

**Comment by clwgh** [comment]
Hi, sorry for the delay in getting around to this. Thankyou for your interest in the script and the extra functionality you've added, for taking the time to create pull requests for them, and the considered approach you've used.

If you don't mind I'm not going to merge the changes. This is purely because I'm using this repo just as a baseline for the raw fetching and parsing of the data from the html. FlightAware may change how the site page is structured which will break the parsing logic, requring it to be reworked, so this repo just focuses on that logic and not on specific implementations.

I intend to use this baseline at some point to create a new script to perform stats comparisons across sites and I'll create a dedicated repo for that.

By all means please do continue to add functionality and maintain your fork of it. Are you active in the forum? If so, feel free to add a post to [the thread](https://discussions.flightaware.com/t/api-endpoint-for-aircraft-and-positions-reported-totals/88489/2), linking to your version as it is bound to be useful to people. If you're not in the forum let me know and I'll post a link to it if you'd like.
